name: CanaConnect
favicon: null
layout_spectrum: 0.9641215810552239
typography_spectrum: 0.3022919150535017
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.04816056462004781
  lightness: 0.05237513384781778
  saturation: 0.9368978880811483
  rhythmicContrast: 0.7991374123375863
purpose: []
